### ISSUE TITLE
Prettier, ESLint, Husky, Github Actions CI 세팅

### ISSUE THREAD

**Issue by justwaves** [f-lab-edu/develect#10]
## Issue Description

- Prettier, ESLint 관련 설정과 함께 PR 요청 시 Github Actions로 체크할 수 있도록 설정합니다

## Todo List
- Prettier 설정
- ESLint 설정
- Husky, Git Hook
  - lint-staged 설정
  - commit-msg 이슈 번호 추가
- Github Actions - PR 요청 시 prettier, lint 체크

**Comment by f-lab-ethan** [comment]
이 이슈에서 yarn berry도 설정해주실 예정일까요?

**Comment by justwaves** [comment]
새로 이슈 생성해서 PR 올리겠습니다~
